### PR TITLE
Fixes logging in with empty or null values

### LINKED ISSUE #40: Sign-in without typing in password gives unhandled error
By signing in, without having made any changes at all in the password field, the application will encounter an unhandled error. Likely caused by the password encoding assuming it to newer being null, and it is not initilized to a value at this time

### PR DESCRIPTION
**Pull request by A-Guldborg**
Fixes #40

### CODE REVIEW

**Review by TTA777 — CHANGES_REQUESTED** [review]
This would fix it yes, but let's rely on the built-in validation from the editForm instead.  We are already using a viewModel with attributes for validation here, so we should be able to rely on that. I must have misconfigured something for the form when I created it, so that it fires the function before it validates if it is correct or not. 

Let's investigate what is causing the bypassing of the existing validation, and fix that instead

**Comment by A-Guldborg** [comment]
Ah, thanks for the hint! The bypassing is caused by adding the login method call to the button's `OnClick` as well as on the `OnValidSubmit`.

The only downside to this solution is that the button is enabled despite the empty field, and only on attempted submit the field will show that the password cannot be empty.

**Review by TTA777 — APPROVED** [review]
Nice find, all good for me then. If the enabled button annoys you, you can look into the [example](https://www.mudblazor.com/components/form#simple-form-validation). At least one of them has a disable button until the form is valid, though we may need to change the form type then. Also not something that bothers me

**Comment by A-Guldborg** [comment]
> Nice find, all good for me then. If the enabled button annoys you, you can look into the [example](https://www.mudblazor.com/components/form#simple-form-validation). At least one of them has a disable button until the form is valid, though we may need to change the form type then. Also not something that bothers me

I just tried to see if it was possible, but I am not able to change that behaviour without introducing other unwanted behaviour.

What we can do, but gives other behaviour, is: Change the EditForm to use Context instead of Model. `OnInitialized` should then initialize the `EditContext` with an initialized `LoginForm` (instead of applying the LoginForm to the EditForm initially). This allows us to bind the `Disabled` property of the submit button to the `EditContext.Validate()`.

The issue with this is: On load, the button will call the `EditContext.Validate()` and add a validation message to all invalid fields, so the page loads with:
> The Email field is required.
> The Password field is required.

The current version only validates each field individually on field changes and I couldn't figure out a way to combine this with the button disabled/enabled without adding much more code complexity. It might, as you say, require us to change away from the EditForm but I don't think that is worth it. I'll merge this but if our PO wants it in the future we have some idea of how to fix it / what our options are.

**Pull request merged**
